apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: sftp
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: sftp
      name: sftp
    spec:
      ports:
      - name: ssh
        port: 2222
        protocol: TCP
        targetPort: ssh
      selector:
        deploymentConfig: sftp
      sessionAffinity: None
      type: NodePort
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: sftp
    spec:
      replicas: 1
      selector:
        deployment-config.name: sftp
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          creationTimestamp: null
          labels:
            deployment-config.name: sftp
            deploymentConfig: sftp
        spec:
          containers:
          - env:
            - name: SSH_GENERATE_HOSTKEYS
              value: "false"
            - name: SSH_USERNAME
              value: sftpuser
            image: amimof/sftp
            imagePullPolicy: Always
            name: sftp
            ports:
            - containerPort: 22
              name: ssh
              protocol: TCP
            readinessProbe:
              tcpSocket:
                port: 22
              initialDelaySeconds: 5
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: sftp
          serviceAccountName: sftp
          terminationGracePeriodSeconds: 30
      test: false
      triggers: []